# Generated by Django 5.2.5 on 2025-09-23 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="category",
            field=models.ForeignKey(
                blank=True,
                max_length=100,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="complaints.category",
            ),
        ),
    ]
