# Generated by Django 5.2.5 on 2026-05-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0003_alter_complaint_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="post",
            new_name="complaint",
        ),
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("IN_PROGRESS", "In Progress"),
                    ("RESOLVED", "Resolved"),
                    ("REJECTED", "Rejected"),
                ],
                default="SUBMITTED",
                max_length=20,
            ),
        ),
    ]
